language: ruby
bundler_args: "--without development"
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.3
  - 2.3.0
  - 2.4.0
script:
  - gem build xmlhasher.gemspec
  - gem install xmlhasher-*
